### ISSUE TITLE
Set pdf page size from config

### ISSUE THREAD

**Issue by theiskaa** [theiskaa/markdown2pdf#12]
The tool currently generates PDFs with fixed **A4 dimensions**. These dimensions are not configurable unless manually modified in the source code.

It would be great to define custom PDF dimensions through a configuration file (`~/markdown2pdfrc.toml`). This would allow greater flexibility for different use cases, such as generating US Letter-sized PDFs or custom page dimensions for specialized documents.

### Example Configuration  
Extend the `~/markdown2pdfrc.toml` file with a section for PDF dimensions:  
```toml  
[pdf]  
page_width = "x"  
page_height = "y"  
```

or to make it more simple, we can use layouts.

```toml  
[pdf]  
page_layout = "A4"  
```
